import type { EditorProject } from "@/types/editor";

/**
 * Seed project used while the backend does not exist yet.
 *
 * Ids are hardcoded on purpose: the same tree has to render on the server and on
 * the client. Once designs are persisted this is replaced by a fetch, but the
 * shape of the data stays identical.
 *
 * Three pages, not one, and deliberately unalike: a tall photostrip, a square
 * card, and a landscape one. A project that seeds a single page lets a
 * multi-page editor look finished while every part of it that has to cope with
 * *differences between* pages — the strip, the fit-to-screen maths, per-page
 * orientation — is never once exercised by the thing developers look at all day.
 */
export const MOCK_PROJECT: EditorProject = {
  id: "prj_demo",
  title: "Wisuda 2026 — Photostrip",
  updatedAt: "2026-01-01T00:00:00.000Z",
  pages: [
    {
      id: "page_1",
      name: "Photostrip",
      width: 1200,
      height: 1800,
      background: {
        type: "gradient",
        from: "#fdf2f8",
        to: "#ede9fe",
        angle: 135,
      },
      objects: [
        {
          id: "slot_1",
          kind: "slot",
          name: "Slot foto 1",
          x: 100,
          y: 120,
          width: 1000,
          height: 480,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          shape: "rect",
          cornerRadius: 24,
          borderWidth: 8,
          borderColor: "#ffffff",
          fill: "#e2e8f0",
          photo: {
            src: "/samples/photo-1.svg",
            offsetX: 0,
            offsetY: 0,
            scale: 1,
          },
        },
        {
          id: "slot_2",
          kind: "slot",
          name: "Slot foto 2",
          x: 100,
          y: 640,
          width: 1000,
          height: 480,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          shape: "rect",
          cornerRadius: 24,
          borderWidth: 8,
          borderColor: "#ffffff",
          fill: "#e2e8f0",
          photo: {
            src: "/samples/photo-2.svg",
            offsetX: 0,
            offsetY: 0,
            scale: 1,
          },
        },
        {
          id: "slot_3",
          kind: "slot",
          name: "Slot foto 3",
          x: 100,
          y: 1160,
          width: 1000,
          height: 480,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          shape: "rect",
          cornerRadius: 24,
          borderWidth: 8,
          borderColor: "#ffffff",
          fill: "#e2e8f0",
          photo: null,
        },
        {
          id: "text_1",
          kind: "text",
          name: "Judul",
          x: 100,
          y: 1680,
          width: 1000,
          height: 80,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          text: "WISUDA 2026",
          fontFamily: "var(--font-geist-sans)",
          fontSize: 64,
          fontWeight: 700,
          letterSpacing: 8,
          lineHeight: 1.2,
          align: "center",
          fill: "#4c1d95",
        },
        {
          id: "sticker_1",
          kind: "sticker",
          name: "Stiker toga",
          x: 940,
          y: 40,
          width: 140,
          height: 140,
          rotation: -12,
          opacity: 1,
          locked: false,
          visible: true,
          content: "🎓",
        },
      ],
    },
    {
      id: "page_2",
      name: "Kartu ucapan",
      // Square: a different aspect ratio to the strip, so anything that assumes
      // one shape breaks where somebody can see it.
      width: 1200,
      height: 1200,
      background: { type: "solid", color: "#0f172a" },
      objects: [
        {
          id: "slot_4",
          kind: "slot",
          name: "Foto utama",
          x: 100,
          y: 100,
          width: 1000,
          height: 760,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          shape: "rect",
          cornerRadius: 32,
          borderWidth: 0,
          borderColor: "#ffffff",
          fill: "#1e293b",
          photo: null,
        },
        {
          id: "text_2",
          kind: "text",
          name: "Ucapan",
          x: 100,
          y: 920,
          width: 1000,
          height: 180,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          text: "Terima kasih sudah datang!",
          fontFamily: "var(--font-geist-sans)",
          fontSize: 72,
          fontWeight: 700,
          letterSpacing: 0,
          lineHeight: 1.2,
          align: "center",
          fill: "#f8fafc",
        },
      ],
    },
    {
      id: "page_3",
      name: "Sampul",
      // Landscape, and empty on purpose: an editor should be looked at with at
      // least one page that has nothing on it, because that is the state every
      // new page starts in.
      width: 1800,
      height: 1200,
      background: {
        type: "gradient",
        from: "#1e293b",
        to: "#4c1d95",
        angle: 160,
      },
      objects: [],
    },
  ],
};
