import type { EditorProject } from "@/types/editor";

/**
 * Seed project used while the backend does not exist yet.
 *
 * Ids are hardcoded on purpose: the same tree has to render on the server and on
 * the client. Once designs are persisted this is replaced by a fetch, but the
 * shape of the data stays identical.
 */
export const MOCK_PROJECT: EditorProject = {
  id: "prj_demo",
  title: "Wisuda 2026 — Photostrip",
  updatedAt: "2026-01-01T00:00:00.000Z",
  pages: [
    {
      id: "page_1",
      name: "Photostrip",
      width: 1200,
      height: 1800,
      background: {
        type: "gradient",
        from: "#fdf2f8",
        to: "#ede9fe",
        angle: 135,
      },
      objects: [
        {
          id: "slot_1",
          kind: "slot",
          name: "Slot foto 1",
          x: 100,
          y: 120,
          width: 1000,
          height: 480,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          shape: "rect",
          cornerRadius: 24,
          borderWidth: 8,
          borderColor: "#ffffff",
          fill: "#e2e8f0",
          photo: {
            src: "/samples/photo-1.svg",
            offsetX: 0,
            offsetY: 0,
            scale: 1,
          },
        },
        {
          id: "slot_2",
          kind: "slot",
          name: "Slot foto 2",
          x: 100,
          y: 640,
          width: 1000,
          height: 480,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          shape: "rect",
          cornerRadius: 24,
          borderWidth: 8,
          borderColor: "#ffffff",
          fill: "#e2e8f0",
          photo: {
            src: "/samples/photo-2.svg",
            offsetX: 0,
            offsetY: 0,
            scale: 1,
          },
        },
        {
          id: "slot_3",
          kind: "slot",
          name: "Slot foto 3",
          x: 100,
          y: 1160,
          width: 1000,
          height: 480,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          shape: "rect",
          cornerRadius: 24,
          borderWidth: 8,
          borderColor: "#ffffff",
          fill: "#e2e8f0",
          photo: null,
        },
        {
          id: "text_1",
          kind: "text",
          name: "Judul",
          x: 100,
          y: 1680,
          width: 1000,
          height: 80,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          text: "WISUDA 2026",
          fontFamily: "var(--font-geist-sans)",
          fontSize: 64,
          fontWeight: 700,
          letterSpacing: 8,
          lineHeight: 1.2,
          align: "center",
          fill: "#4c1d95",
        },
        {
          id: "sticker_1",
          kind: "sticker",
          name: "Stiker toga",
          x: 940,
          y: 40,
          width: 140,
          height: 140,
          rotation: -12,
          opacity: 1,
          locked: false,
          visible: true,
          content: "🎓",
        },
      ],
    },
    {
      id: "page_2",
      name: "Kartu ucapan",
      width: 1800,
      height: 1200,
      background: { type: "solid", color: "#0f172a" },
      objects: [
        {
          id: "slot_4",
          kind: "slot",
          name: "Slot foto utama",
          x: 120,
          y: 160,
          width: 800,
          height: 880,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          shape: "rect",
          cornerRadius: 32,
          borderWidth: 0,
          borderColor: "#ffffff",
          fill: "#1e293b",
          photo: {
            src: "/samples/photo-3.svg",
            offsetX: 0,
            offsetY: 0,
            scale: 1,
          },
        },
        {
          id: "slot_5",
          kind: "slot",
          name: "Slot foto bulat",
          x: 1040,
          y: 160,
          width: 360,
          height: 360,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          shape: "circle",
          cornerRadius: 0,
          borderWidth: 12,
          borderColor: "#a78bfa",
          fill: "#1e293b",
          photo: null,
        },
        {
          id: "text_2",
          kind: "text",
          name: "Ucapan",
          x: 1040,
          y: 600,
          width: 640,
          height: 200,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          text: "Selamat menempuh\nhidup baru, teman!",
          fontFamily: "var(--font-geist-sans)",
          fontSize: 56,
          fontWeight: 600,
          letterSpacing: 0,
          lineHeight: 1.3,
          align: "left",
          fill: "#f8fafc",
        },
      ],
    },
  ],
};
